-- MySQL Script generated by MySQL Workbench
-- Sun Apr  3 20:21:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `agenda`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agenda`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`contato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(45) NULL DEFAULT NULL,
  `apelido` VARCHAR(45) NULL DEFAULT NULL,
  `empresa` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `aniversario` DATE NULL DEFAULT NULL,
  `observacao` MEDIUMTEXT NULL DEFAULT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contato_usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_contato_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `agenda`.`usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agenda`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `identificador` VARCHAR(10) NULL DEFAULT NULL,
  `contato` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_Clientes_idx` (`contato` ASC) VISIBLE,
  CONSTRAINT `fk_email_Clientes`
    FOREIGN KEY (`contato`)
    REFERENCES `agenda`.`contato` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agenda`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` MEDIUMTEXT NULL DEFAULT NULL,
  `identificador` VARCHAR(45) NULL DEFAULT NULL,
  `contato` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefones_Clientes1_idx` (`contato` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_Clientes10`
    FOREIGN KEY (`contato`)
    REFERENCES `agenda`.`contato` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agenda`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` FLOAT NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `descricao` VARCHAR(500) NULL DEFAULT NULL,
  `contato` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicos_Clientes1_idx` (`contato` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_Clientes1`
    FOREIGN KEY (`contato`)
    REFERENCES `agenda`.`contato` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `agenda`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`telefones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NULL DEFAULT NULL,
  `identificador` VARCHAR(20) NULL DEFAULT NULL,
  `contato` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefones_Clientes1_idx` (`contato` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_Clientes1`
    FOREIGN KEY (`contato`)
    REFERENCES `agenda`.`contato` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
